// Array of Top 100 U.S. Metropolitan Area Names (Shortened)
export const metroAreas: string[] = [
  "Remote",
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Dallas-Fort Worth, TX",
  "Houston, TX",
  "Washington, DC",
  "Miami, FL",
  "Philadelphia, PA",
  "Atlanta, GA",
  "Boston, MA",
  "Phoenix, AZ",
  "San Francisco, CA",
  "Riverside, CA",
  "Detroit, MI",
  "Seattle, WA",
  "Minneapolis, MN",
  "San Diego, CA",
  "Tampa, FL",
  "Denver, CO",
  "Baltimore, MD",
  "St. Louis, MO",
  "Charlotte, NC",
  "Orlando, FL",
  "San Antonio, TX",
  "Portland, OR",
  "Sacramento, CA",
  "Pittsburgh, PA",
  "Las Vegas, NV",
  "Austin, TX",
  "Cleveland, OH",
  "Kansas City, MO",
  "Indianapolis, IN",
  "San Jose, CA",
  "Nashville, TN",
  "Columbus, OH",
  "Fort Worth, TX",
  "Cincinnati, OH",
  "Milwaukee, WI",
  "Richmond, VA",
  "Oklahoma City, OK",
  "Providence, RI",
  "Jacksonville, FL",
  "Salt Lake City, UT",
  "Birmingham, AL",
  "Grand Rapids, MI",
  "Raleigh, NC",
  "Omaha, NE",
  "Virginia Beach, VA",
  "Memphis, TN",
  "Louisville, KY",
  "Hartford, CT",
  "New Orleans, LA",
  "Wichita, KS",
  "Lexington, KY",
  "Bakersfield, CA",
  "Tucson, AZ",
  "Honolulu, HI",
  "Stockton, CA",
  "Corpus Christi, TX",
  "Henderson, NV",
  "Greensboro, NC",
  "Plano, TX",
  "Lincoln, NE",
  "Buffalo, NY",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "St. Petersburg, FL",
  "Chandler, AZ",
  "Laredo, TX",
  "Madison, WI",
  "Durham, NC",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Winston-Salem, NC",
  "North Las Vegas, NV",
  "Norfolk, VA",
  "Fremont, CA",
  "Irving, TX",
  "Chesapeake, VA",
  "Garland, TX",
  "Hialeah, FL",
  "Boise, ID",
  "Baton Rouge, LA",
  "Spokane, WA",
  "Des Moines, IA",
  "Tacoma, WA",
  "Modesto, CA",
  "Fontana, CA",
  "Santa Clarita, CA",
  "Oxnard, CA",
  "Moreno Valley, CA",
  "Fayetteville, AR",
  "Yonkers, NY",
  "Huntington Beach, CA",
  "Amarillo, TX",
  "Mobile, AL",
  "Grand Prairie, TX",
  "Huntington, WV",
  "Augusta, GA",
  "Little Rock, AR",
  "Columbus, GA",
  "Fort Collins, CO",
  "West Palm Beach, FL",
  "McAllen, TX",
  "Knoxville, TN",
  "Springfield, MO",
  "Vancouver, WA",
  "Pembroke Pines, FL",
];
